# Generated by Django 3.0.1 on 2020-03-07 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 22, 4, 42, 913498)),
        ),
    ]
