# Generated by Django 3.0.1 on 2021-03-13 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 12, 10, 51, 702172)),
        ),
    ]
