# Generated by Django 3.0.1 on 2020-03-08 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessaging', '0002_auto_20200307_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 15, 0, 14, 918013)),
        ),
    ]
