# Generated by Django 2.1.7 on 2019-12-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='last_name',
        ),
        migrations.AddField(
            model_name='stories',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=255, verbose_name="friend's name"),
        ),
    ]
