# Generated by Django 2.1.7 on 2019-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0002_auto_20191227_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='story_image',
        ),
        migrations.AddField(
            model_name='stories',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='story_images/', verbose_name="Friend's Image"),
        ),
    ]
