# Generated by Django 3.0.1 on 2020-02-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0002_auto_20200205_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='story_images/'),
        ),
    ]
