# Generated by Django 2.1.7 on 2019-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0003_auto_20191227_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='Image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='story_images/'),
        ),
    ]
