# Generated by Django 3.0.1 on 2020-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0003_auto_20200208_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
    ]
