# Generated by Django 2.1.7 on 2019-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0004_auto_20191227_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='story_images/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
