# Generated by Django 2.1.7 on 2019-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0006_auto_20191227_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('NOT_APPROVED', 'not_approved'), ('PENDING', 'pending')], default='NOT_APPROVED', max_length=50),
        ),
    ]
