# Generated by Django 2.1.7 on 2019-12-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0008_auto_20191227_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='Image',
            new_name='image',
        ),
    ]
