# Generated by Django 2.1.7 on 2019-12-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0009_auto_20191227_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='story_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='created_date',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='approval_status',
        ),
    ]
