# Generated by Django 2.1.7 on 2020-01-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0010_auto_20191230_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='comment count'),
        ),
    ]
