# Generated by Django 2.1.7 on 2020-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0013_stories_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
