# Generated by Django 2.1.7 on 2020-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplestory', '0014_stories_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
